// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3172.Samuel.subsystems;

import org.usfirst.frc3172.Samuel.RobotMap;

import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.Joystick.AxisType;
import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class RobotLeftRightDrive extends Subsystem {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    SpeedController middleWheel = RobotMap.robotLeftRightDriveMiddleWheel;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

	double left = -1;//Might be backwards in which case change ones to negative ones
	double right = 1;//Might be backwards in which case change ones to positive ones
	double currentSpeed = 0;
	double increment = 0.2;
	double max = 0.8;
	double min = -0.8;

	// Put methods for controlling this subsystem
	// here. Call these from Commands.
	public void stop() {
		middleWheel.set(0);
		currentSpeed = 0;
	}

	public void left() {
		if (currentSpeed > min){ 
			currentSpeed += (left * increment);
			middleWheel.set(currentSpeed);
		}
		else {
			middleWheel.set(currentSpeed);
		}
		//middleWheel.set(-0.2);
	}

	public void right() {
		if (currentSpeed < max){ 
			currentSpeed += (right * increment);
			middleWheel.set(currentSpeed);
		}
		else {
			middleWheel.set(currentSpeed);
		}
		//middleWheel.set(0.2);
	}

	public void initDefaultCommand() {
		// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

		// Set the default command for a subsystem here.
		//setDefaultCommand(new MySpecialCommand());
	}
}

