// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3172.Samuel;
    
import edu.wpi.first.wpilibj.*;

import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController driveLeftMotor;
    public static SpeedController driveRightMotor;
    public static RobotDrive driveRobotDrive21;
    public static SpeedController robotLeftRightDriveMiddleWheel;
    public static SpeedController elevatorElevatorMotor;
    public static DigitalInput elevatorElevatorUp;
    public static DigitalInput elevatorElevatorDown;
    public static SpeedController clawClawMotor;
    public static DigitalInput clawClawOpen;
    public static DigitalInput clawClawClose;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveLeftMotor = new Victor(0);
        LiveWindow.addActuator("Drive", "Left Motor", (Victor) driveLeftMotor);
        
        driveRightMotor = new Victor(1);
        LiveWindow.addActuator("Drive", "Right Motor", (Victor) driveRightMotor);
        
        driveRobotDrive21 = new RobotDrive(driveLeftMotor, driveRightMotor);
        
        driveRobotDrive21.setSafetyEnabled(true);
        driveRobotDrive21.setExpiration(0.1);
        driveRobotDrive21.setSensitivity(0.5);
        driveRobotDrive21.setMaxOutput(1.0);
        

        robotLeftRightDriveMiddleWheel = new Victor(2);
        LiveWindow.addActuator("Robot Left Right Drive", "Middle Wheel", (Victor) robotLeftRightDriveMiddleWheel);
        
        elevatorElevatorMotor = new Talon(3);
        LiveWindow.addActuator("Elevator", "ElevatorMotor", (Talon) elevatorElevatorMotor);
        
        elevatorElevatorUp = new DigitalInput(0);
        LiveWindow.addSensor("Elevator", "Elevator Up", elevatorElevatorUp);
        
        elevatorElevatorDown = new DigitalInput(1);
        LiveWindow.addSensor("Elevator", "Elevator Down", elevatorElevatorDown);
        
        clawClawMotor = new Talon(4);
        LiveWindow.addActuator("Claw", "ClawMotor", (Talon) clawClawMotor);
        
        clawClawOpen = new DigitalInput(2);
        LiveWindow.addSensor("Claw", "Claw Open", clawClawOpen);
        
        clawClawClose = new DigitalInput(3);
        LiveWindow.addSensor("Claw", "Claw Close", clawClawClose);
        

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
